"""empty message

Revision ID: 580a10be23fb
Revises: 1481d137db60
Create Date: 2022-08-29 19:27:09.868001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '580a10be23fb'
down_revision = '1481d137db60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('days_on_zillow', sa.String(), nullable=True))
    op.drop_column('property', 'dats_on_zillow')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('dats_on_zillow', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('property', 'days_on_zillow')
    # ### end Alembic commands ###
